<div class="uwp-content-wrap">
    <div class="uwp-profile-header">
        <div class="uwp-profile-header-img"></div>
        <div class="uwp-profile-avatar"><img src="https://scontent-ord1-1.xx.fbcdn.net/v/t1.0-1/p160x160/13962739_10153746894693038_5612035079295632737_n.jpg?oh=42a426803f16a89c63cd0b33d688a17a&amp;oe=5869ED83"></div>
    </div>

    <div class="uwp-profile">
        <div class="uwp-profile-name">
            <h2>Pol Tajani</h2>
        </div>
        <div class="uwp-profile-bio">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua… <a href="#">More</a></div>
        <div class="uwp-profile-social"><i class="fa fa-facebook-official"></i> &nbsp; <i class="fa fa-twitter-square"></i> </div>
        <div class="uwp-profile-map"><img src="https://maps.googleapis.com/maps/api/staticmap?center=Brooklyn+Bridge,New+York,NY&amp;zoom=13&amp;size=600x300&amp;maptype=roadmap&#10;&amp;markers=color:blue%7Clabel:S%7C40.702147,-74.015794&amp;markers=color:green%7Clabel:G%7C40.711614,-74.012318&#10;&amp;markers=color:red%7Clabel:C%7C40.718217,-73.998284&#10;&amp;key=AIzaSyABvMvjh07i55MIuOhQcwoL8cagSc5-X0k" style="width:100%;margin:10px 0"></div>
    </div>

    <div class="uwp-profile-content">
        <div class="uwp-profile-nav">
            <ul>
                <li class="uwp-profile-posts active"><a href="#"><span class="uwp-profile-post-label ">POSTS</span><span class="uwp-profile-post-count">13</span></a></li>
                <li class="uwp-profile-comments"><a href="#"><span class="uwp-profile-comment-label">COMMENTS</span><span class="uwp-profile-comment-count">27</span></a></li>
            </ul>
            <div class="uwp-edit-account"><a href="#" title="Edit Account"><i class="fa fa-gear"></i></a></div>
        </div>
        <div class="clfx"></div>
        <div class="uwp-profile-entries">
            <h3>Pol Tajani’s Posts</h3>
            <div class="rpwe-block "><ul class="rpwe-ul"><li class="rpwe-li rpwe-clearfix"><a class="rpwe-img" href="http://dropct.com/costa-rica/" rel="bookmark"><img class="rpwe-alignleft rpwe-thumb" src="http://dropct.com/wp-content/uploads/2016/09/about-us-80x80.jpg" alt="Costa Rica"></a><h3 class="rpwe-title"><a href="http://dropct.com/costa-rica/" title="Permalink to Costa Rica" rel="bookmark">Costa Rica</a></h3><time class="rpwe-time published" datetime="2016-09-07T21:22:34+00:00">September 7, 2016</time><div class="rpwe-summary">2020<a href="http://dropct.com/costa-rica/" class="more-link">&nbsp;Read More »</a></div></li><li class="rpwe-li rpwe-clearfix"><a class="rpwe-img" href="http://dropct.com/geneva/" rel="bookmark"><img class="rpwe-alignleft rpwe-thumb" src="http://dropct.com/wp-content/uploads/2016/07/Geneva-aerial-view-80x80.jpg" alt="Geneva"></a><h3 class="rpwe-title"><a href="http://dropct.com/geneva/" title="Permalink to Geneva" rel="bookmark">Geneva</a></h3><time class="rpwe-time published" datetime="2016-07-22T20:57:47+00:00">July 22, 2016</time><div class="rpwe-summary">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do …<a href="http://dropct.com/geneva/" class="more-link">&nbsp;Read More »</a></div></li><li class="rpwe-li rpwe-clearfix"><a class="rpwe-img" href="http://dropct.com/hello-world/" rel="bookmark"><img class="rpwe-alignleft rpwe-thumb" src="http://dropct.com/wp-content/uploads/2016/07/71_-_Carthagène_-_Décembre_2008-80x80.jpg" alt="Hello world!"></a><h3 class="rpwe-title"><a href="http://dropct.com/hello-world/" title="Permalink to Hello world!" rel="bookmark">Hello world!</a></h3><time class="rpwe-time published" datetime="2016-07-22T20:36:14+00:00">July 22, 2016</time><div class="rpwe-summary">Welcome to WordPress. This is your first post. Edit or …<a href="http://dropct.com/hello-world/" class="more-link">&nbsp;Read More »</a></div></li></ul></div><!-- Generated by http://wordpress.org/plugins/recent-posts-widget-extended/ -->
            <div class="uwp-profile-post-nav">
                <span><a class="active" href="#">1</a></span><span><a href="#">2</a></span><span><a href="#">3</a></span><span><a href="#">4</a></span><span><a href="#">5</a></span>
            </div>
        </div>
    </div>
</div>